---
# =============================================================================
# Promtail - Log Collection DaemonSet
# =============================================================================
# Promtail runs on every node and collects logs from:
# - Container logs (/var/log/pods/*)
# - Systemd journals
# - Application logs
#
# Sends logs to Loki with labels:
# - namespace
# - pod
# - container
# - app
# - environment
# =============================================================================

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: promtail
  namespace: observability
  labels:
    app: promtail
    component: logging
spec:
  selector:
    matchLabels:
      app: promtail
      component: logging

  template:
    metadata:
      labels:
        app: promtail
        component: logging
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3101"

    spec:
      serviceAccountName: promtail
      securityContext:
        runAsUser: 0
        runAsGroup: 0

      containers:
        - name: promtail
          image: grafana/promtail:2.9.3
          imagePullPolicy: IfNotPresent

          args:
            - -config.file=/etc/promtail/promtail.yaml

          ports:
            - name: http-metrics
              containerPort: 3101
              protocol: TCP

          env:
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName

          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi

          volumeMounts:
            - name: config
              mountPath: /etc/promtail

            # Mount container logs
            - name: varlog
              mountPath: /var/log
              readOnly: true

            # Mount pod logs
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true

            # For position tracking
            - name: positions
              mountPath: /run/promtail

      volumes:
        - name: config
          configMap:
            name: promtail-config

        - name: varlog
          hostPath:
            path: /var/log

        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers

        - name: positions
          hostPath:
            path: /run/promtail
            type: DirectoryOrCreate

      tolerations:
        # Run on all nodes including master
        - effect: NoSchedule
          operator: Exists

---
# =============================================================================
# Promtail - ServiceAccount
# =============================================================================

apiVersion: v1
kind: ServiceAccount
metadata:
  name: promtail
  namespace: observability
  labels:
    app: promtail
    component: logging

---
# =============================================================================
# Promtail - ClusterRole
# =============================================================================

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: promtail
  labels:
    app: promtail
    component: logging
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
      - nodes/proxy
      - services
      - endpoints
      - pods
    verbs:
      - get
      - list
      - watch

---
# =============================================================================
# Promtail - ClusterRoleBinding
# =============================================================================

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: promtail
  labels:
    app: promtail
    component: logging
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: promtail
subjects:
  - kind: ServiceAccount
    name: promtail
    namespace: observability
