---
# =============================================================================
# Authentication Service - HorizontalPodAutoscaler
# =============================================================================
# Auto-scales the authentication service based on CPU and memory utilization.
#
# Scaling behavior:
# - Min replicas: 2 (for high availability)
# - Max replicas: 6 (to handle peak load)
# - Target CPU: 70%
# - Target Memory: 80%
#
# Prerequisites:
# - Metrics Server must be installed and running
# =============================================================================

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: authentication-service
  namespace: orange-wallet
  labels:
    app: authentication-service
    component: backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: authentication-service

  minReplicas: 2
  maxReplicas: 6

  metrics:
    # CPU-based scaling
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70

    # Memory-based scaling
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80

  # Scaling behavior
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300  # 5 minutes
      policies:
        - type: Percent
          value: 50
          periodSeconds: 60
        - type: Pods
          value: 1
          periodSeconds: 60
      selectPolicy: Min

    scaleUp:
      stabilizationWindowSeconds: 60  # 1 minute
      policies:
        - type: Percent
          value: 100
          periodSeconds: 30
        - type: Pods
          value: 2
          periodSeconds: 30
      selectPolicy: Max
