---
# =============================================================================
# Authentication Service - RSA Keys Secret
# =============================================================================
# RSA public and private keys for JWT token signing.
#
# IMPORTANT SECURITY NOTES:
# 1. This Secret contains REAL RSA keys currently embedded in the Docker image
# 2. Keys are base64-encoded in this manifest (standard K8s Secret format)
# 3. In production, use SealedSecrets, External Secrets Operator, or GCP Secret Manager
# 4. This is a transitional solution - migrate to GCP Secret Manager (ESO)
#
# Migration Path:
# Current:  Embedded in Docker image → K8s Secret (this file)
# Target:   GCP Secret Manager → External Secrets Operator → K8s Secret
#
# Key Rotation:
# To rotate keys:
# 1. Generate new RSA keypair: openssl genrsa -out private.pem 2048
# 2. Extract public key: openssl rsa -in private.pem -pubout -out public.pem
# 3. Base64 encode and update this Secret
# 4. Apply changes and restart authentication-service pods
# =============================================================================

apiVersion: v1
kind: Secret
metadata:
  name: authentication-rsa-keys
  namespace: orange-wallet
  labels:
    app: authentication-service
    component: security
type: Opaque
stringData:
  public.pem: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAso1kee1IXIuKFS1N7cPA
    KTYNFKzJD0IHAWt6dRf2rP4BWI3LchkJopJD7VH6415bNCQMOO4Vnv0+HHYgwyAA
    +Dk4b80fN4zdpOXzNp/IC9u0fRhYa09jK5S38s1aPeQCO3kpTyploA1dcETxjfaW
    sRvU1M9yhVCvcmEC3LIN2vm6bWX4Ad1FH4W9cPBXqVsPUDv9aONIVBWDCUGhIiE0
    3BD/KWGQciW67A0YQTPukkLccga2gUxxnRkwQDtcJ9raWiAFHZcEakky5rGdm4np
    oT5qy/9pJIsZl1p1WzNrjOTIvdaqRbhnYhoxh4NBDgg3IU5iCGNz2yqV03AxMU6F
    CQIDAQAB
    -----END PUBLIC KEY-----
  private.pem: |
    -----BEGIN PRIVATE KEY-----
    MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCyjWR57Uhci4oV
    LU3tw8ApNg0UrMkPQgcBa3p1F/as/gFYjctyGQmikkPtUfrjXls0JAw47hWe/T4c
    diDDIAD4OThvzR83jN2k5fM2n8gL27R9GFhrT2MrlLfyzVo95AI7eSlPKmWgDV1w
    RPGN9paxG9TUz3KFUK9yYQLcsg3a+bptZfgB3UUfhb1w8FepWw9QO/1o40hUFYMJ
    QaEiITTcEP8pYZByJbrsDRhBM+6SQtxyBraBTHGdGTBAO1wn2tpaIAUdlwRqSTLm
    sZ2biemhPmrL/2kkixmXWnVbM2uM5Mi91qpFuGdiGjGHg0EOCDchTmIIY3PbKpXT
    cDExToUJAgMBAAECggEAEdN5945QDiVESO73+8fyVGr4DVtey24tIuAnHq+gyg6l
    9cBaUm7bfmaZ74SixrZx5pe+vKRQdkoUPGUyyihU0HNuBgN1nWcr7b2jdY2oPD7Y
    GzEmCrinTv+PCeeknc84xdVH4YZ7FOqgrIfFkgXPb6k2q3R2m4a9rW6wCXahWX4w
    PlNoy9s7bxpaSmz+Iwf39Y0CIb5kkye1nksvo73mJhKDeUu6sJlw3L5w9wPpo4ss
    S4tHP8RVtiMJub2Y8NMaTToJUT7CWGy4qSS1LqBzs5vB/JfpvJjfrJ9BJ1nFsF/Z
    uIUBgsbjI9Nk1H/KvT3htWmYnb5tmTDU3LxIjkOSgQKBgQDvg9uJLNvBIkgrTKuk
    NRk+nbSLpEM02xGrWsCCiD4IpA39EAWgdRmoys9GHu/U5U/cMZpBXu7GlfoEfDXs
    E7nsSjCotRIu8dJHzagi0xO3uTIxGNd72g322ZdbNbDmiawTVYLpIEUVGEbuI5Dk
    jNMYwlW9zKv1dEfoReiJRgBK0QKBgQC+12ZksCX4Lf/kqqeCvdk7fY3Vlm+0QhxE
    D1ksunVFzuTcJ43IxYXF59UDpjP0cvjgTAWGlSNaGOUJEd5xHla5ErMgBrOQ6j1c
    aU8IU7mEf6Rmwk0zbG0VYUWEY3LoJs4MSpouALIfH4JnWef70ta1xriNaN2+0V54
    R81T2wY0uQKBgQCN69K84JDCSv76cS7PWQtBWA8wI0ATZK9+moKxles0EYmcZs7+
    ugRfSPUytogj3VDJx7aAf7D6iMmhuLv2y+WCBp/4h3pjyLRyCYFUSUBIv/rmrrKY
    V6eomlweFp1grTkCJ8wvOQjWLBFzcC2dz3gSFqzZjxphkeo9zpawKINp0QKBgAb7
    nrWEdH82P6zASczQ4Yf5uhzcmk3ANYSQAzVNxUi+n0Um9VspTxHEv9iYVkJViqG6
    ZmFcR6TeUFMaokcFUysGciNz21IsH/6no8qsNZeRjBRue6CsEPm9S2vir6uq79Mn
    T6jrQZk97+mUMpbWSiDwmoQiGCsJQimohuzQkNORAoGBANUp1+J38w++YsG6ccYw
    mV/mFQjXCEAr9exX+xwDx+TupzkYMq27Hp+fvV1u3kpvrv1yW0enSQJ0f4FiGjor
    A0/B9Uw4572i8BjZL65YyLxkKGUFj5Cdq0yxqgd6UmTAtldYcxtHCwHifDu2x7Ez
    w6Gb6ZhmxRe0BNIAM1BROtlC
    -----END PRIVATE KEY-----
