# =============================================================================
# Orange Wallet Application Secrets
# =============================================================================
# IMPORTANT: This file contains sensitive data placeholders.
# Before applying to cluster, replace <PLACEHOLDER> values with actual secrets.
#
# To apply secrets:
#   kubectl apply -f app-secrets.yaml
#
# To create secret from command line (alternative):
#   kubectl create secret generic orange-wallet-secrets \
#     --from-literal=DB_PASSWORD=<your-password> \
#     --from-literal=SMTP_PASSWORD=<your-smtp-password> \
#     -n orange-wallet
# =============================================================================

apiVersion: v1
kind: Secret
metadata:
  name: orange-wallet-secrets
  namespace: orange-wallet
  labels:
    app.kubernetes.io/name: orange-wallet
    app.kubernetes.io/component: secrets
    app.kubernetes.io/managed-by: argocd
type: Opaque
stringData:
  # ===== Database Credentials =====
  DB_USERNAME: "orange_wallet"
  DB_PASSWORD: "mikasaAckerman"  # TODO: Replace with actual password

  # ===== SMTP / Email Credentials =====
  SMTP_HOST: "smtp.gmail.com"
  SMTP_PORT: "587"
  SMTP_MAIL: "orange.wallet.bni@gmail.com"
  SMTP_PASSWORD: "sieonmdpjasazdgc"  # TODO: Replace with actual SMTP app password
  MAIL_USERNAME: "orange.wallet.bni@gmail.com"
  MAIL_PASSWORD: "sieonmdpjasazdgc"  # TODO: Same as SMTP_PASSWORD

  # ===== Redis =====
  REDIS_HOST: "redis.database.svc.cluster.local"
  REDIS_PORT: "6379"
  # REDIS_PASSWORD: ""  # Uncomment if Redis has password

  # ===== Kafka =====
  KAFKA_BOOTSTRAP_SERVERS: "kafka.orange-wallet.svc.cluster.local:9092"

  # ===== BNI VA Integration =====
  BNI_VA_BASE_URL: "https://api-sandbox.bni.co.id"
  BNI_VA_CLIENT_ID: "dummy-client-id"  # TODO: Replace with actual BNI client ID
  BNI_VA_CLIENT_SECRET: "secret-key-for-dev"  # TODO: Replace with actual BNI client secret
  BNI_VA_MOCK_ENABLED: "true"
  BNI_API_KEY: "bni-api-key-dev"  # TODO: Replace with actual BNI API key

  # ===== WAHA (WhatsApp) =====
  WAHA_BASE_URL: "http://waha.orange-wallet.svc.cluster.local:3000"
  WAHA_API_KEY: "f5010a544c324fc483623e2031b2b92f"  # TODO: Replace with actual WAHA API key
  WAHA_SESSION_NAME: "default"
  WAHA_WEBHOOK_HMAC_SECRET: "64eb6963dd30bbe9786cb9193f9eabee6ddac7e9aeb0deb6fc72a1bd065abb52"  # TODO: Replace

  # ===== Application Secrets =====
  INVITE_SECRET: "9evyY2Iopik4onDHa+ygvSoI97DJnUx+2JEOeO9ROUE="  # TODO: Replace with secure random key
  WALLET_DELETE_SECRET: "9evyY2Iopik4onDHa+ygvSoI97DJnUx+2JEOeO9ROUE="  # TODO: Replace with secure random key

  # ===== Google reCAPTCHA =====
  RECAPTCHA_ENABLED: "false"
  RECAPTCHA_SECRET: "6LeNJP4rAAAAAGyGNK-K1D8i7UsLx0ev2Q1RADJc"  # TODO: Replace with actual reCAPTCHA secret
  RECAPTCHA_HOSTNAME: "localhost"
  RECAPTCHA_SCORE_THRESHOLD: "0.5"

  # ===== GCP Storage (if enabled) =====
  GCS_ENABLED: "false"
  GCS_BUCKET_NAME: "orange-wallet-users-profiles"
  GCP_PROJECT_ID: "orange-wallet-project"
  GCS_SERVICE_ACCOUNT_EMAIL: "orange-wallet-storage@orange-wallet-project.iam.gserviceaccount.com"

---
# =============================================================================
# PostgreSQL Secret (for database pod itself)
# =============================================================================
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
  namespace: database
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/component: database
type: Opaque
stringData:
  postgres-password: "mikasaAckerman"  # Root postgres user password
  password: "mikasaAckerman"  # orange_wallet user password
  username: "orange_wallet"
  database: "orange_wallet_db"
