# ==============================================================================
# Cloudflare Origin Certificate - Manual Secret Creation
# ==============================================================================
# This is a TEMPLATE. Replace <BASE64_ENCODED_...> with actual values.
#
# Steps to create:
# 1. Generate Cloudflare Origin Certificate:
#    - Cloudflare Dashboard → SSL/TLS → Origin Server → Create Certificate
#    - Hostnames: orangebybni.my.id, *.orangebybni.my.id
#    - Validity: 15 years
#
# 2. Base64 encode:
#    cat origin-cert.pem | base64 -w 0 > cert.b64
#    cat origin-key.pem | base64 -w 0 > key.b64
#
# 3. Apply to cluster:
#    kubectl apply -f cloudflare-origin-cert.yaml -n orange-wallet
#    kubectl apply -f cloudflare-origin-cert.yaml -n observability
#
# OR use kubectl create (recommended):
#    kubectl create secret tls cloudflare-origin-tls \
#      --cert=origin-cert.pem \
#      --key=origin-key.pem \
#      -n orange-wallet
# ==============================================================================

---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-origin-tls
  namespace: orange-wallet
  labels:
    app.kubernetes.io/name: cloudflare-origin-tls
    app.kubernetes.io/managed-by: manual
type: kubernetes.io/tls
data:
  tls.crt: <BASE64_ENCODED_CERTIFICATE>
  tls.key: <BASE64_ENCODED_PRIVATE_KEY>

---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-origin-tls
  namespace: observability
  labels:
    app.kubernetes.io/name: cloudflare-origin-tls
    app.kubernetes.io/managed-by: manual
type: kubernetes.io/tls
data:
  tls.crt: <BASE64_ENCODED_CERTIFICATE>
  tls.key: <BASE64_ENCODED_PRIVATE_KEY>
