---
# =============================================================================
# ExternalSecret - Redis Credentials
# =============================================================================
# This ExternalSecret syncs Redis credentials from GCP Secret Manager.
#
# Required GCP Secrets (create these first):
# 1. redis-password: Redis password for authentication
#
# Create GCP secret:
#   echo -n "your-secure-redis-password" | gcloud secrets create redis-password \
#     --data-file=- --replication-policy=automatic
# =============================================================================

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: redis-credentials
  namespace: database
  labels:
    app: redis
    component: cache
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore

  target:
    name: redis-credentials
    creationPolicy: Owner
    deletionPolicy: Retain

  data:
    - secretKey: password
      remoteRef:
        key: redis-password

---
# =============================================================================
# ExternalSecret - Redis Connection
# =============================================================================
# Provides Redis connection details for application services.
# =============================================================================

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: redis-connection
  namespace: orange-wallet
  labels:
    app.kubernetes.io/name: redis-connection
    app.kubernetes.io/component: cache-config
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore

  target:
    name: redis-connection
    creationPolicy: Owner

    template:
      engineVersion: v2
      data:
        # Redis connection URL
        redis-url: "redis://:{{ .password }}@redis-master.database.svc.cluster.local:6379/0"

        # Individual components
        host: "redis-master.database.svc.cluster.local"
        port: "6379"
        password: "{{ .password }}"
        database: "0"

  data:
    - secretKey: password
      remoteRef:
        key: redis-password
