---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: waha-sessions-pvc
  namespace: orange-wallet
  labels:
    app: waha
    component: messaging
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Lightweight - sessions only
  storageClassName: local-path  # K3s default storage class
