---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: messaging
  labels:
    app: kafka
    component: messaging
spec:
  serviceName: kafka
  replicas: 1
  selector:
    matchLabels:
      app: kafka
      component: messaging

  template:
    metadata:
      labels:
        app: kafka
        component: messaging
    spec:
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:7.6.1
          ports:
            - name: internal
              containerPort: 29092
              protocol: TCP
            - name: external
              containerPort: 9092
              protocol: TCP
            - name: controller
              containerPort: 9093
              protocol: TCP

          env:
            # KRaft mode configuration
            - name: KAFKA_PROCESS_ROLES
              value: "broker,controller"

            - name: KAFKA_NODE_ID
              value: "1"

            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: "1@kafka-0.kafka.messaging.svc.cluster.local:9093"

            # Listener configuration
            - name: KAFKA_LISTENERS
              value: "INTERNAL://:29092,CONTROLLER://:9093,EXTERNAL://:9092"

            - name: KAFKA_ADVERTISED_LISTENERS
              value: "INTERNAL://kafka-0.kafka.messaging.svc.cluster.local:29092,EXTERNAL://kafka.messaging.svc.cluster.local:9092"

            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "INTERNAL"

            - name: KAFKA_CONTROLLER_LISTENER_NAMES
              value: "CONTROLLER"

            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"

            # Cluster configuration
            - name: CLUSTER_ID
              value: "v8xF6a1cRMi5zR6AK1bldA"

            # Topic configuration
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"

            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: "1"

            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_INSYNC_REPLICAS
              value: "1"

            - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
              value: "true"

            - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
              value: "0"

          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi

          volumeMounts:
            - name: kafka-data
              mountPath: /var/lib/kafka/data

          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - kafka-broker-api-versions --bootstrap-server localhost:9092
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3

          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - kafka-broker-api-versions --bootstrap-server localhost:9092
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 3

  volumeClaimTemplates:
    - metadata:
        name: kafka-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
