---
# =============================================================================
# Certificate - Orange Wallet TLS Certificate
# =============================================================================
# Automatically requests and renews TLS certificate from Let's Encrypt.
#
# Lifecycle:
#   1. Cert-Manager creates CertificateRequest
#   2. ACME challenge initiated (HTTP-01 via Ingress)
#   3. Let's Encrypt verifies domain ownership
#   4. Certificate issued and stored in Secret
#   5. Ingress uses Secret for TLS termination
#   6. Auto-renewal 30 days before expiry
#
# DNS Configuration Required:
#   - api.orangebybni.my.id → Load Balancer IP
#   - orangebybni.my.id → Load Balancer IP
#
# Certificate Validity: 90 days (Let's Encrypt standard)
# Auto-Renewal: 30 days before expiry
# =============================================================================

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: orange-wallet-tls
  namespace: orange-wallet
  labels:
    app.kubernetes.io/name: orange-wallet-tls
    app.kubernetes.io/part-of: orange-wallet
spec:
  # Secret name where certificate will be stored
  # Ingress will reference this secret for TLS
  secretName: orange-wallet-tls-secret

  # Certificate issuer
  # Start with 'letsencrypt-staging' for testing
  # Switch to 'letsencrypt-prod' after verification
  issuerRef:
    name: letsencrypt-staging  # Change to 'letsencrypt-prod' when ready
    kind: ClusterIssuer
    group: cert-manager.io

  # Common Name (primary domain)
  commonName: api.orangebybni.my.id

  # Subject Alternative Names (SANs)
  # All domains that should be covered by this certificate
  dnsNames:
  - api.orangebybni.my.id
  - orangebybni.my.id
  - www.orangebybni.my.id

  # Certificate duration (Let's Encrypt issues 90-day certs)
  duration: 2160h  # 90 days

  # Renew certificate 30 days before expiry
  renewBefore: 720h  # 30 days

  # Private key configuration
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
    rotationPolicy: Always  # Rotate key on renewal

  # X.509 certificate fields
  subject:
    organizations:
    - Orange Wallet
    organizationalUnits:
    - Engineering
    countries:
    - ID
    localities:
    - Jakarta

  # Certificate usages
  usages:
  - digital signature
  - key encipherment
  - server auth

---
# =============================================================================
# Certificate - Development/Testing (Self-Signed)
# =============================================================================
# Self-signed certificate for development and testing.
# Instant generation, no external dependencies.
#
# Use Case:
#   - Local development
#   - CI/CD testing
#   - Environments without public DNS
#
# Browser Warning: Browsers will show "Not Secure" warning
# =============================================================================

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: orange-wallet-tls-selfsigned
  namespace: orange-wallet
  labels:
    app.kubernetes.io/name: orange-wallet-tls-selfsigned
    app.kubernetes.io/part-of: orange-wallet
    environment: dev
spec:
  secretName: orange-wallet-tls-selfsigned-secret

  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io

  commonName: localhost

  dnsNames:
  - localhost
  - orange-wallet.local
  - api.orange-wallet.local

  # IP SANs for direct IP access
  ipAddresses:
  - 127.0.0.1

  duration: 8760h  # 1 year
  renewBefore: 720h  # 30 days

  privateKey:
    algorithm: RSA
    size: 2048

  usages:
  - digital signature
  - key encipherment
  - server auth
  - client auth
