---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBaa1nyVarawRUxgatDg/5gQIYmyifFScVm6N/mQPxxeXucyyV2qZeugGDCfLE6OQ/0DxTuO1zeELbiob7GZx0Eu6Xdivgt0s0TTkt29kjiNQgRh/gs4Y9BkPHiTVj9/Egoda/3UqEsTx40FBE92cM0SHl2K4jFRw0ROLdi3Hybms8Y3tyCCPeRO7d6Vb59dlJv50EoTHKeIHAxfH+qzNxdsoJttRqIBHVOQ18tePcrBKDP25ilyqyccvk+epBfdxIeeCKJHbXa4YINejWRsEGIoDmggDbQRd0Lezz8s//5Ov+JZxgEpyDp9yA4x+ySXq8zdUk+eneCzOMOzZ1HiyqcGf5dJlFo+QlLyT1kY3u7dTwdW6mpCPgNIYFRBD2/QqfY4hcZfnXfDYJavju3RGVZHWEbbE2IVFW5cYAbhMDA9P6LYyi9BmL6gIgp1h/lbqf4QRo9fwiANJkSupcKlpUp/440iHyfNsJIa/lYe3UBUxeG4DKj5okEybh/SQpbvDOWCCm9Owb3I8QYroIIZ09Eh4lRUixtlfvY0TGP2WS1CCuU0Apd5k4a9plUTFYGi32loq2/zjZPCk5dJgtqCDW5sjgq75voyVjTZGJ9swf00fJDK1bjq59CilWhZOx0HH3dboCGq+STYZa4NvjVq/tFq686X7CozyeNQMwP0Y4VUvHRHfDOibvASTivuyiKZNlNPuCnKxZcClwbGKIvLunY5a8afG6Gt/YqTecqGEM0jOGlXkdbmOgN
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: cert-manager
