---
# =============================================================================
# ArgoCD Application - Authentication Service
# =============================================================================
# Automatic sync enabled for GitOps continuous deployment
# =============================================================================

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentication-service
  namespace: argocd
  labels:
    app.kubernetes.io/name: authentication-service
    app.kubernetes.io/part-of: orange-wallet
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/group-2-odp-bni/orange-wallet-gitops.git
    targetRevision: main
    path: production/authentication-service

  destination:
    server: https://kubernetes.default.svc
    namespace: orange-wallet

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  revisionHistoryLimit: 10

  # Ignore HPA-managed replica count
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
