---
# =============================================================================
# ExternalSecret - PostgreSQL Credentials
# =============================================================================
# This ExternalSecret syncs PostgreSQL credentials from GCP Secret Manager
# to a Kubernetes Secret that can be used by PostgreSQL StatefulSet and
# application services.
#
# Required GCP Secrets (create these first):
# 1. postgres-password: PostgreSQL superuser password
# 2. postgres-app-username: Application database user
# 3. postgres-app-password: Application database user password
#
# Create GCP secrets:
#   echo -n "your-secure-postgres-password" | gcloud secrets create postgres-password \
#     --data-file=- --replication-policy=automatic
#
#   echo -n "orange_wallet_user" | gcloud secrets create postgres-app-username \
#     --data-file=- --replication-policy=automatic
#
#   echo -n "your-secure-app-password" | gcloud secrets create postgres-app-password \
#     --data-file=- --replication-policy=automatic
# =============================================================================

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-credentials
  namespace: database
  labels:
    app: postgresql
    component: database
spec:
  # Refresh interval for secret sync
  refreshInterval: 1h

  # Reference to ClusterSecretStore
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore

  # Target Kubernetes secret
  target:
    name: postgres-credentials
    creationPolicy: Owner
    deletionPolicy: Retain

  # Data to fetch from GCP Secret Manager
  data:
    # PostgreSQL superuser password
    - secretKey: password
      remoteRef:
        key: postgres-password

    # Application database user credentials
    - secretKey: app-username
      remoteRef:
        key: postgres-app-username

    - secretKey: app-password
      remoteRef:
        key: postgres-app-password

---
# =============================================================================
# ExternalSecret - PostgreSQL Connection String
# =============================================================================
# This creates a connection string for application services to use.
# The connection string is assembled from multiple secrets and configuration.
# =============================================================================

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-connection
  namespace: orange-wallet
  labels:
    app.kubernetes.io/name: postgres-connection
    app.kubernetes.io/component: database-config
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore

  target:
    name: postgres-connection
    creationPolicy: Owner

    # Template to create connection string
    template:
      engineVersion: v2
      data:
        # JDBC URL for Spring Boot applications
        jdbc-url: "jdbc:postgresql://postgresql.database.svc.cluster.local:5432/orange_wallet_db"

        # Standard connection string
        database-url: "postgresql://{{ .app_username }}:{{ .app_password }}@postgresql.database.svc.cluster.local:5432/orange_wallet_db"

        # Individual components
        host: "postgresql.database.svc.cluster.local"
        port: "5432"
        database: "orange_wallet_db"
        username: "{{ .app_username }}"
        password: "{{ .app_password }}"

  dataFrom:
    - extract:
        key: postgres-app-username
        property: app-username

    - extract:
        key: postgres-app-password
        property: app-password
