---
# =============================================================================
# MongoDB - StatefulSet
# =============================================================================
# MongoDB database for ML Engine (split bill feature)
# =============================================================================

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: database
  labels:
    app: mongodb
    component: database
spec:
  serviceName: mongodb
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
      component: database

  template:
    metadata:
      labels:
        app: mongodb
        component: database
    spec:
      nodeSelector:
        workload-type: stateful

      tolerations:
        - key: "stateful"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"

      securityContext:
        fsGroup: 999
        runAsUser: 999
        runAsNonRoot: true

      containers:
        - name: mongodb
          image: mongo:7-jammy
          imagePullPolicy: IfNotPresent

          ports:
            - name: mongodb
              containerPort: 27017
              protocol: TCP

          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-credentials
                  key: root-username

            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-credentials
                  key: root-password

            - name: MONGO_INITDB_DATABASE
              value: "split_bill_db"

          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi

          livenessProbe:
            exec:
              command:
                - mongosh
                - --quiet
                - --eval
                - "db.adminCommand('ping')"
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3

          readinessProbe:
            exec:
              command:
                - mongosh
                - --quiet
                - --eval
                - "db.adminCommand('ping')"
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3

          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
            - name: mongodb-config
              mountPath: /data/configdb

  volumeClaimTemplates:
    - metadata:
        name: mongodb-data
        labels:
          app: mongodb
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: local-path
        resources:
          requests:
            storage: 10Gi

    - metadata:
        name: mongodb-config
        labels:
          app: mongodb
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: local-path
        resources:
          requests:
            storage: 1Gi
